### ISSUE TITLE
The great TODO list...

### ISSUE THREAD

**Issue by ryanrox333** [2WatchGH/Docs#1]
- [x] Start App (Overwolf)
- [x] Start API (http[s]) (basic grabbing system for heroes and cache them)
- [x] Get app approved on Overwolf
- [ ] Cache servers (save data and get it from either redis/http[s])

**APP:**
- [x] Design prototypes (preferably in figma for right now)
- [ ] Start building the app's infastructure.
- [ ] Cache system inside the app to send to the backend.
- [ ] Show stats from other users before the game starts.

**API:**
- [ ] http(s) server
- [ ] grab information from caching server
- [ ] hero information from latest updates
- [ ] post requests? (used for like when the game updates send an announcement on discord or whatever)
- [ ] panel?

**Comment by ryanrox333** [comment]
I have a VPS already planned out for production, it should be able to handle up to 100gbs worth of caching for now.

**Comment by ryanrox333** [comment]
The average user file (JSON) is around 200 or so bytes, so if we store only 300 bytes/user then we should have more than enough space with the 100 gbs.

~333,333,333 users.

**Comment by ryanrox333** [comment]
I know for a fact we won't be storing 333 million users so splitting the 100gbs of caching to 50gbs to players and 50gbs to game info is our best bet.

**Comment by devHazz** [comment]
Caching wise, we could just create a routine to sweep some of the cache every 7 days or so? It does not need to be stored indefinitely.

**Comment by ryanrox333** [comment]
I'd say for the users we can, just not with the game data since that'll be used probably forever now.

**Comment by devHazz** [comment]
Yeah, for game data, we can store in a DB or something since nothing is gonna change quickly and so we don't push too many requests via the scrape
